CREATE TABLE "MOUVEMENT"
  (
    "ID" NUMBER NOT NULL ENABLE,
    "DATE_MVT" TIMESTAMP (0) NOT NULL ENABLE,
    "TYPE"       NUMBER DEFAULT 0 NOT NULL ENABLE,
    "PRODUIT_ID" NUMBER NOT NULL ENABLE,
    "QUANTITY"   NUMBER DEFAULT 1 NOT NULL ENABLE,
    "COMMENTAIRE" NVARCHAR2(255) NOT NULL ENABLE,
    CONSTRAINT "MOUVEMENT_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;