CREATE TABLE "PRODUIT"
  (
    "ID" NUMBER NOT NULL ENABLE,
    "NAME" NVARCHAR2(255) NOT NULL ENABLE,
    "PRICE"           NUMBER NOT NULL ENABLE,
    "MINSTOCK"        NUMBER NOT NULL ENABLE,
    "COMMANDQUANTITY" NUMBER(10,0) NOT NULL ENABLE,
    "MARQUE_ID"       NUMBER DEFAULT 0 NOT NULL ENABLE,
    "TYPE_ID"         NUMBER DEFAULT 0 NOT NULL ENABLE,
    CONSTRAINT "PRODUIT_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;