CREATE TABLE "UTILISATEUR"
  (
    "ID" NUMBER NOT NULL ENABLE,
    "EMAIL" NVARCHAR2(255),
    "PASSWORD" NVARCHAR2(255),
    CONSTRAINT "UTILISATEUR_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS" ENABLE
  )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  TABLESPACE "USERS" ;

CREATE OR REPLACE TRIGGER "TRIGGER_PK_UTILISATEUR" before
  INSERT ON UTILISATEUR FOR EACH row BEGIN IF :new.id IS NULL THEN
  SELECT SEQ_UTILISATEURID.nextval INTO :new.id FROM sys.dual;
END IF;
END;
/
ALTER TRIGGER "TRIGGER_PK_UTILISATEUR" ENABLE;