SET DEFINE OFF;
INSERT INTO TYPE VALUES ('1' , 'Disques serveurs (NAS)');
INSERT INTO TYPE VALUES ('2' , 'Rangements CD/DVD');
INSERT INTO TYPE VALUES ('3' , 'Néons & Cables Ronds');
INSERT INTO TYPE VALUES ('4' , 'Tablettes');
INSERT INTO TYPE VALUES ('5' , 'Tablettes graphique');
INSERT INTO TYPE VALUES ('6' , 'Cartes réseaux');
INSERT INTO TYPE VALUES ('7' , 'Téléphonie IP');
INSERT INTO TYPE VALUES ('8' , 'Jeux Vidéo PSP');
INSERT INTO TYPE VALUES ('9' , 'Navigation GPS');
INSERT INTO TYPE VALUES ('10' , 'Dictaphones');
INSERT INTO TYPE VALUES ('11' , 'Périphériques de jeu');
INSERT INTO TYPE VALUES ('12' , 'Packs Appareil Photo');
INSERT INTO TYPE VALUES ('13' , 'Lecteurs & enregistreurs Blu-Ray de salon');
INSERT INTO TYPE VALUES ('14' , 'Adaptateurs TNT');
INSERT INTO TYPE VALUES ('15' , 'Jeux Vidéo PC');
INSERT INTO TYPE VALUES ('16' , 'Jeux Vidéo Playstation 3');
INSERT INTO TYPE VALUES ('17' , 'Alimentations');
INSERT INTO TYPE VALUES ('18' , 'Graveurs Blu-Ray/HD-DVD');
INSERT INTO TYPE VALUES ('19' , 'Clés USB');
INSERT INTO TYPE VALUES ('20' , 'Stockages amovibles');
INSERT INTO TYPE VALUES ('21' , 'Watercooling');
INSERT INTO TYPE VALUES ('22' , 'Accessoires refroidissement');
INSERT INTO TYPE VALUES ('23' , 'Onduleurs');
INSERT INTO TYPE VALUES ('24' , 'Télécommandes');
INSERT INTO TYPE VALUES ('25' , 'Caméras');
INSERT INTO TYPE VALUES ('26' , 'Cartes graphiques');
INSERT INTO TYPE VALUES ('27' , 'Objectifs Appareils photo');
INSERT INTO TYPE VALUES ('28' , 'Jeux Vidéo Nintendo 3DS');
INSERT INTO TYPE VALUES ('29' , 'Accessoires MP3');
INSERT INTO TYPE VALUES ('30' , 'Accessoires Navigation GPS');
INSERT INTO TYPE VALUES ('31' , 'Radios');
INSERT INTO TYPE VALUES ('32' , 'Logiciels Mac');
INSERT INTO TYPE VALUES ('33' , 'Appareils photo');
INSERT INTO TYPE VALUES ('34' , 'Lecteurs DVD de Salon');
INSERT INTO TYPE VALUES ('35' , 'Disques durs (HDD)');
INSERT INTO TYPE VALUES ('36' , 'Cartes son');
INSERT INTO TYPE VALUES ('37' , 'Cartes d''acquisition');
INSERT INTO TYPE VALUES ('38' , 'CD vierges');
INSERT INTO TYPE VALUES ('39' , 'Ventilateurs');
INSERT INTO TYPE VALUES ('40' , 'Lecteurs DVD');
INSERT INTO TYPE VALUES ('41' , 'Ventilateurs lumineux');
INSERT INTO TYPE VALUES ('42' , 'Net Top');
INSERT INTO TYPE VALUES ('43' , 'Portables Apple');
INSERT INTO TYPE VALUES ('44' , 'Souris');
INSERT INTO TYPE VALUES ('45' , 'Tapis de souris');
INSERT INTO TYPE VALUES ('46' , 'Casques & Micros');
INSERT INTO TYPE VALUES ('47' , 'Connectique externe');
INSERT INTO TYPE VALUES ('48' , 'Accessoires Apple');
INSERT INTO TYPE VALUES ('49' , 'Cadres photos numériques');
INSERT INTO TYPE VALUES ('50' , 'Téléphones fixes');
INSERT INTO TYPE VALUES ('51' , 'Lecteurs MP3 / MP4');
INSERT INTO TYPE VALUES ('52' , 'Logiciels PC');
INSERT INTO TYPE VALUES ('53' , 'Postes cassette / CD');
INSERT INTO TYPE VALUES ('54' , 'Baladeurs CD');
INSERT INTO TYPE VALUES ('55' , 'Accessoires Tablette');
INSERT INTO TYPE VALUES ('56' , 'Accessoires consoles');
INSERT INTO TYPE VALUES ('57' , 'Consoles');
INSERT INTO TYPE VALUES ('58' , 'Cartes mères');
INSERT INTO TYPE VALUES ('59' , 'Disques Flash (SSD)');
INSERT INTO TYPE VALUES ('60' , 'Graveurs DVD');
INSERT INTO TYPE VALUES ('61' , 'Racks & Boîtiers Externes');
INSERT INTO TYPE VALUES ('62' , 'Graveurs externes');
INSERT INTO TYPE VALUES ('63' , 'Blu-Ray/HD-DVD Vierges');
INSERT INTO TYPE VALUES ('64' , 'Boîtiers & Accessoires');
INSERT INTO TYPE VALUES ('65' , 'Réseaux sans fil');
INSERT INTO TYPE VALUES ('66' , 'Connectique interne');
INSERT INTO TYPE VALUES ('67' , 'CPL - Courant porteur en ligne');
INSERT INTO TYPE VALUES ('68' , 'Jeux Vidéo Nintendo DS');
INSERT INTO TYPE VALUES ('69' , 'Vidéoprojecteurs');
INSERT INTO TYPE VALUES ('70' , 'Packs Home Cinéma');
INSERT INTO TYPE VALUES ('71' , 'Boîtiers');
INSERT INTO TYPE VALUES ('72' , 'Cartes contrôleur');
INSERT INTO TYPE VALUES ('73' , 'Disques durs multimédia');
INSERT INTO TYPE VALUES ('74' , 'Ventirads CPU');
INSERT INTO TYPE VALUES ('75' , 'Ventirads GPU');
INSERT INTO TYPE VALUES ('76' , 'Mini PC');
INSERT INTO TYPE VALUES ('77' , 'Ordinateurs Apple');
INSERT INTO TYPE VALUES ('78' , 'Hubs / Switchs');
INSERT INTO TYPE VALUES ('79' , 'Serveurs d''impression');
INSERT INTO TYPE VALUES ('80' , 'Cartes mémoire');
INSERT INTO TYPE VALUES ('81' , 'Lecteurs de cartes mémoire');
INSERT INTO TYPE VALUES ('82' , 'Moniteurs LCD');
INSERT INTO TYPE VALUES ('83' , 'Scanners');
INSERT INTO TYPE VALUES ('84' , 'Claviers');
INSERT INTO TYPE VALUES ('85' , 'Connectique réseau');
INSERT INTO TYPE VALUES ('86' , 'KVM');
INSERT INTO TYPE VALUES ('87' , 'Enceintes');
INSERT INTO TYPE VALUES ('88' , 'Autoradios');
INSERT INTO TYPE VALUES ('89' , 'Téléviseurs LCD, LCD LED & Plasma');
INSERT INTO TYPE VALUES ('90' , 'Liseuses électroniques (Ebook)');
INSERT INTO TYPE VALUES ('91' , 'Téléphones portables');
INSERT INTO TYPE VALUES ('92' , 'Mémoire vive');
INSERT INTO TYPE VALUES ('93' , 'Disques durs externes');
INSERT INTO TYPE VALUES ('94' , 'DVD Vierges');
INSERT INTO TYPE VALUES ('95' , 'Autres accessoires');
INSERT INTO TYPE VALUES ('96' , 'Imprimantes');
INSERT INTO TYPE VALUES ('97' , 'Routeurs / Firewalls');
INSERT INTO TYPE VALUES ('98' , 'Jeux Vidéo Wii');
INSERT INTO TYPE VALUES ('99' , 'Assistants d''Aide à la Conduite');
INSERT INTO TYPE VALUES ('100', 'Jeux Vidéo Playstation 2');
INSERT INTO TYPE VALUES ('101', 'Accessoires Appareils photo');
INSERT INTO TYPE VALUES ('102', 'Jeux Vidéo Xbox 360');
INSERT INTO TYPE VALUES ('103', 'Processeurs');
INSERT INTO TYPE VALUES ('104', 'Cartes / Boitiers Tuner TV');
INSERT INTO TYPE VALUES ('105', 'Lecteurs Blu-Ray/HD-DVD');
INSERT INTO TYPE VALUES ('106', 'Grilles & Filtres');
INSERT INTO TYPE VALUES ('107', 'Régulateurs de ventilation');
INSERT INTO TYPE VALUES ('108', 'Modems');
INSERT INTO TYPE VALUES ('109', 'Caméscopes');
INSERT INTO TYPE VALUES ('110', 'Jeux Vidéo Mac');
INSERT INTO TYPE VALUES ('111', 'Enregistreurs DVD');
