SET DEFINE OFF;
INSERT INTO TYPE VALUES ('1' , '115' , 'Disques serveurs (NAS)');
INSERT INTO TYPE VALUES ('2' , '117' , 'Rangements CD/DVD');
INSERT INTO TYPE VALUES ('3' , '119' , 'Néons & Cables Ronds');
INSERT INTO TYPE VALUES ('4' , '120' , 'Tablettes');
INSERT INTO TYPE VALUES ('5' , '123' , 'Tablettes graphique');
INSERT INTO TYPE VALUES ('6' , '125' , 'Cartes réseaux');
INSERT INTO TYPE VALUES ('7' , '128' , 'Téléphonie IP');
INSERT INTO TYPE VALUES ('8' , '133' , 'Jeux Vidéo PSP');
INSERT INTO TYPE VALUES ('9' , '130' , 'Navigation GPS');
INSERT INTO TYPE VALUES ('10' , '129' , 'Dictaphones');
INSERT INTO TYPE VALUES ('11' , '132' , 'Périphériques de jeu');
INSERT INTO TYPE VALUES ('12' , '127' , 'Packs Appareil Photo');
INSERT INTO TYPE VALUES ('13' , '131' , 'Lecteurs & enregistreurs Blu-Ray de salon');
INSERT INTO TYPE VALUES ('14' , '131' , 'Adaptateurs TNT');
INSERT INTO TYPE VALUES ('15' , '133' , 'Jeux Vidéo PC');
INSERT INTO TYPE VALUES ('16' , '133' , 'Jeux Vidéo Playstation 3');
INSERT INTO TYPE VALUES ('17' , '112' , 'Alimentations');
INSERT INTO TYPE VALUES ('18' , '114' , 'Graveurs Blu-Ray/HD-DVD');
INSERT INTO TYPE VALUES ('19' , '115' , 'Clés USB');
INSERT INTO TYPE VALUES ('20' , '115' , 'Stockages amovibles');
INSERT INTO TYPE VALUES ('21' , '118' , 'Watercooling');
INSERT INTO TYPE VALUES ('22' , '118' , 'Accessoires refroidissement');
INSERT INTO TYPE VALUES ('23' , '126' , 'Onduleurs');
INSERT INTO TYPE VALUES ('24' , '123' , 'Télécommandes');
INSERT INTO TYPE VALUES ('25' , '124' , 'Caméras');
INSERT INTO TYPE VALUES ('26' , '112' , 'Cartes graphiques');
INSERT INTO TYPE VALUES ('27' , '127' , 'Objectifs Appareils photo');
INSERT INTO TYPE VALUES ('28' , '133' , 'Jeux Vidéo Nintendo 3DS');
INSERT INTO TYPE VALUES ('29' , '129' , 'Accessoires MP3');
INSERT INTO TYPE VALUES ('30' , '130' , 'Accessoires Navigation GPS');
INSERT INTO TYPE VALUES ('31' , '129' , 'Radios');
INSERT INTO TYPE VALUES ('32' , '134' , 'Logiciels Mac');
INSERT INTO TYPE VALUES ('33' , '127' , 'Appareils photo');
INSERT INTO TYPE VALUES ('34' , '131' , 'Lecteurs DVD de Salon');
INSERT INTO TYPE VALUES ('35' , '114' , 'Disques durs (HDD)');
INSERT INTO TYPE VALUES ('36' , '112' , 'Cartes son');
INSERT INTO TYPE VALUES ('37' , '112' , 'Cartes d''acquisition');
INSERT INTO TYPE VALUES ('38' , '117' , 'CD vierges');
INSERT INTO TYPE VALUES ('39' , '118' , 'Ventilateurs');
INSERT INTO TYPE VALUES ('40' , '116' , 'Lecteurs DVD');
INSERT INTO TYPE VALUES ('41' , '119' , 'Ventilateurs lumineux');
INSERT INTO TYPE VALUES ('42' , '120' , 'Net Top');
INSERT INTO TYPE VALUES ('43' , '120' , 'Portables Apple');
INSERT INTO TYPE VALUES ('44' , '123' , 'Souris');
INSERT INTO TYPE VALUES ('45' , '123' , 'Tapis de souris');
INSERT INTO TYPE VALUES ('46' , '124' , 'Casques & Micros');
INSERT INTO TYPE VALUES ('47' , '126' , 'Connectique externe');
INSERT INTO TYPE VALUES ('48' , '126' , 'Accessoires Apple');
INSERT INTO TYPE VALUES ('49' , '127' , 'Cadres photos numériques');
INSERT INTO TYPE VALUES ('50' , '128' , 'Téléphones fixes');
INSERT INTO TYPE VALUES ('51' , '129' , 'Lecteurs MP3 / MP4');
INSERT INTO TYPE VALUES ('52' , '134' , 'Logiciels PC');
INSERT INTO TYPE VALUES ('53' , '129' , 'Postes cassette / CD');
INSERT INTO TYPE VALUES ('54' , '129' , 'Baladeurs CD');
INSERT INTO TYPE VALUES ('55' , '126' , 'Accessoires Tablette');
INSERT INTO TYPE VALUES ('56' , '132' , 'Accessoires consoles');
INSERT INTO TYPE VALUES ('57' , '132' , 'Consoles');
INSERT INTO TYPE VALUES ('58' , '112' , 'Cartes mères');
INSERT INTO TYPE VALUES ('59' , '114' , 'Disques Flash (SSD)');
INSERT INTO TYPE VALUES ('60' , '114' , 'Graveurs DVD');
INSERT INTO TYPE VALUES ('61' , '115' , 'Racks & Boîtiers Externes');
INSERT INTO TYPE VALUES ('62' , '115' , 'Graveurs externes');
INSERT INTO TYPE VALUES ('63' , '117' , 'Blu-Ray/HD-DVD Vierges');
INSERT INTO TYPE VALUES ('64' , '119' , 'Boîtiers & Accessoires');
INSERT INTO TYPE VALUES ('65' , '125' , 'Réseaux sans fil');
INSERT INTO TYPE VALUES ('66' , '126' , 'Connectique interne');
INSERT INTO TYPE VALUES ('67' , '125' , 'CPL - Courant porteur en ligne');
INSERT INTO TYPE VALUES ('68' , '133' , 'Jeux Vidéo Nintendo DS');
INSERT INTO TYPE VALUES ('69' , '131' , 'Vidéoprojecteurs');
INSERT INTO TYPE VALUES ('70' , '131' , 'Packs Home Cinéma');
INSERT INTO TYPE VALUES ('71' , '112' , 'Boîtiers');
INSERT INTO TYPE VALUES ('72' , '114' , 'Cartes contrôleur');
INSERT INTO TYPE VALUES ('73' , '115' , 'Disques durs multimédia');
INSERT INTO TYPE VALUES ('74' , '118' , 'Ventirads CPU');
INSERT INTO TYPE VALUES ('75' , '118' , 'Ventirads GPU');
INSERT INTO TYPE VALUES ('76' , '120' , 'Mini PC');
INSERT INTO TYPE VALUES ('77' , '120' , 'Ordinateurs Apple');
INSERT INTO TYPE VALUES ('78' , '125' , 'Hubs / Switchs');
INSERT INTO TYPE VALUES ('79' , '125' , 'Serveurs d''impression');
INSERT INTO TYPE VALUES ('80' , '115' , 'Cartes mémoire');
INSERT INTO TYPE VALUES ('81' , '116' , 'Lecteurs de cartes mémoire');
INSERT INTO TYPE VALUES ('82' , '122' , 'Moniteurs LCD');
INSERT INTO TYPE VALUES ('83' , '122' , 'Scanners');
INSERT INTO TYPE VALUES ('84' , '123' , 'Claviers');
INSERT INTO TYPE VALUES ('85' , '126' , 'Connectique réseau');
INSERT INTO TYPE VALUES ('86' , '123' , 'KVM');
INSERT INTO TYPE VALUES ('87' , '124' , 'Enceintes');
INSERT INTO TYPE VALUES ('88' , '130' , 'Autoradios');
INSERT INTO TYPE VALUES ('89' , '131' , 'Téléviseurs LCD, LCD LED & Plasma');
INSERT INTO TYPE VALUES ('90' , '127' , 'Liseuses électroniques (Ebook)');
INSERT INTO TYPE VALUES ('91' , '128' , 'Téléphones portables');
INSERT INTO TYPE VALUES ('92' , '112' , 'Mémoire vive');
INSERT INTO TYPE VALUES ('93' , '115' , 'Disques durs externes');
INSERT INTO TYPE VALUES ('94' , '117' , 'DVD Vierges');
INSERT INTO TYPE VALUES ('95' , '119' , 'Autres accessoires');
INSERT INTO TYPE VALUES ('96' , '122' , 'Imprimantes');
INSERT INTO TYPE VALUES ('97' , '125' , 'Routeurs / Firewalls');
INSERT INTO TYPE VALUES ('98' , '133' , 'Jeux Vidéo Wii');
INSERT INTO TYPE VALUES ('99' , '130' , 'Assistants d''Aide à la Conduite');
INSERT INTO TYPE VALUES ('100', '133' , 'Jeux Vidéo Playstation 2');
INSERT INTO TYPE VALUES ('101', '127' , 'Accessoires Appareils photo');
INSERT INTO TYPE VALUES ('102', '133' , 'Jeux Vidéo Xbox 360');
INSERT INTO TYPE VALUES ('103', '112' , 'Processeurs');
INSERT INTO TYPE VALUES ('104', '112' , 'Cartes / Boitiers Tuner TV');
INSERT INTO TYPE VALUES ('105', '116' , 'Lecteurs Blu-Ray/HD-DVD');
INSERT INTO TYPE VALUES ('106', '119' , 'Grilles & Filtres');
INSERT INTO TYPE VALUES ('107', '119' , 'Régulateurs de ventilation');
INSERT INTO TYPE VALUES ('108', '125' , 'Modems');
INSERT INTO TYPE VALUES ('109', '127' , 'Caméscopes');
INSERT INTO TYPE VALUES ('110', '133' , 'Jeux Vidéo Mac');
INSERT INTO TYPE VALUES ('111', '131' , 'Enregistreurs DVD');
INSERT INTO TYPE VALUES ('112', '0' , 'Composants');
INSERT INTO TYPE VALUES ('113', '0' , 'Stockage');
INSERT INTO TYPE VALUES ('114', '113' , 'Stockage interne');
INSERT INTO TYPE VALUES ('115', '113' , 'Stockage externe');
INSERT INTO TYPE VALUES ('116', '113' , 'Lecteurs');
INSERT INTO TYPE VALUES ('117', '113' , 'Médias Vierges');
INSERT INTO TYPE VALUES ('118', '0' , 'Refroidissement');
INSERT INTO TYPE VALUES ('119', '118' , 'Tuning PC');
INSERT INTO TYPE VALUES ('120', '0' , 'Ordinateurs');
INSERT INTO TYPE VALUES ('121', '0' , 'Périphérique');
INSERT INTO TYPE VALUES ('122', '121' , 'Imagerie');
INSERT INTO TYPE VALUES ('123', '121' , 'Périphériques de saisie');
INSERT INTO TYPE VALUES ('124', '121' , 'Multimédia');
INSERT INTO TYPE VALUES ('125', '0' , 'Réseaux');
INSERT INTO TYPE VALUES ('126', '0' , 'Connectique & Accessoires');
INSERT INTO TYPE VALUES ('127', '0' , 'Numérique');
INSERT INTO TYPE VALUES ('128', '0' , 'Téléphonie');
INSERT INTO TYPE VALUES ('129', '0' , 'HiFi Mobile');
INSERT INTO TYPE VALUES ('130', '129' , 'Auto & GPS');
INSERT INTO TYPE VALUES ('131', '0' , 'Vidéo');
INSERT INTO TYPE VALUES ('132', '0' , 'Jeux Vidéos & Logiciels');
INSERT INTO TYPE VALUES ('133', '132' , 'Jeux Vidéo');
INSERT INTO TYPE VALUES ('134', '132' , 'Logiciels');